export const dummyData: any[] = [
  {
    name: 'Harry Potter',
    alternate_names: [],
    species: 'human',
    gender: 'male',
    house: 'Gryffindor',
    dateOfBirth: '31-07-1980',
    yearOfBirth: 1980,
    wizard: true,
    ancestry: 'half-blood',
    eyeColour: 'green',
    hairColour: 'black',
    wand: {
      wood: 'holly',
      core: 'phoenix feather',
      length: 11,
    },
    patronus: 'stag',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Daniel Radcliffe',
    alternate_actors: [],
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/harry.jpg',
  },
]

export const dummyDataForTagNames = [
  {
    alive: true,
    ancestry: 'half-blood',
    dateOfBirth: '31-07-1980',
    eyeColour: 'green',
    gender: 'male',
    hairColour: 'black',
    hogwartsStaff: false,
    hogwartsStudent: true,
    house: 'Gryffindor',
    name: 'Harry Potter',
    patronus: 'stag',
    species: 'human',
    wizard: true,
    yearOfBirth: 1980,
  },
  {
    alive: true,
    ancestry: 'muggleborn',
    dateOfBirth: '19-09-1979',
    eyeColour: 'brown',
    gender: 'female',
    hairColour: 'brown',
    hogwartsStaff: false,
    hogwartsStudent: true,
    house: 'Gryffindor',
    name: 'Hermione Granger',
    patronus: 'otter',
    species: 'human',
    wizard: true,
    yearOfBirth: 1979,
  },
  {
    alive: true,
    ancestry: 'pure-blood',
    dateOfBirth: '01-03-1980',
    eyeColour: 'blue',
    gender: 'male',
    hairColour: 'red',
    hogwartsStaff: false,
    hogwartsStudent: true,
    house: 'Gryffindor',
    name: 'Ron Weasley',
    patronus: 'Jack Russell terrier',
    species: 'human',
    wizard: true,
    yearOfBirth: 1980,
  },
]

export const expectedDummyDataForTagNames = {
  alive: [true],
  ancestry: ['half-blood', 'muggleborn', 'pure-blood'],
  dateOfBirth: ['31-07-1980', '19-09-1979', '01-03-1980'],
  eyeColour: ['green', 'brown', 'blue'],
  gender: ['male', 'female'],
  hairColour: ['black', 'brown', 'red'],
  hogwartsStaff: [false],
  hogwartsStudent: [true],
  house: ['Gryffindor'],
  name: ['Harry Potter', 'Hermione Granger', 'Ron Weasley'],
  patronus: ['stag', 'otter', 'Jack Russell terrier'],
  species: ['human'],
  wizard: [true],
  yearOfBirth: [1980, 1979],
}
