export const dummyData: any[] = [
  {
    name: 'Harry Potter',
    alternate_names: [],
    species: 'human',
    gender: 'male',
    house: 'Gryffindor',
    dateOfBirth: '31-07-1980',
    yearOfBirth: 1980,
    wizard: true,
    ancestry: 'half-blood',
    eyeColour: 'green',
    hairColour: 'black',
    wand: {
      wood: 'holly',
      core: 'phoenix feather',
      length: 11,
    },
    patronus: 'stag',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Daniel Radcliffe',
    alternate_actors: [],
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/harry.jpg',
  },
]

export const dummyDataForTagNames = [
  {
    alive: true,
    ancestry: 'half-blood',
    eyeColour: 'green',
    gender: 'male',
    hairColour: 'black',
    hogwartsStaff: false,
    hogwartsStudent: true,
    house: 'Gryffindor',
    patronus: 'stag',
    species: 'human',
    wizard: true,
  },
  {
    alive: true,
    ancestry: 'muggleborn',
    eyeColour: 'brown',
    gender: 'female',
    hairColour: 'brown',
    hogwartsStaff: false,
    hogwartsStudent: true,
    house: 'Gryffindor',
    patronus: 'otter',
    species: 'human',
    wizard: true,
  },
  {
    alive: true,
    ancestry: 'pure-blood',
    eyeColour: 'blue',
    gender: 'male',
    hairColour: 'red',
    hogwartsStaff: false,
    hogwartsStudent: true,
    house: 'Gryffindor',
    patronus: 'Jack Russell terrier',
    species: 'human',
    wizard: true,
  },
]

export const expectedDummyDataForTagNames = {
  alive: [true],
  ancestry: ['half-blood', 'muggleborn', 'pure-blood'],
  eyeColour: ['green', 'brown', 'blue'],
  gender: ['male', 'female'],
  hairColour: ['black', 'brown', 'red'],
  hogwartsStaff: [false],
  hogwartsStudent: [true],
  house: ['Gryffindor'],
  patronus: ['stag', 'otter', 'Jack Russell terrier'],
  species: ['human'],
  wizard: [true],
}

export const dummyDataForFilteredData = [
  ...dummyDataForTagNames,
  {
    actor: 'David Thewlis',
    alive: false,
    // @ts-ignore
    alternate_actors: [],
    alternate_names: [
      'Professor Lupin',
      'Moony',
      'Remus John Lupin',
    ],
    ancestry: 'half-blood',
    dateOfBirth: '10-03-1960',
    eyeColour: 'green',
    gender: 'male',
    hairColour: 'brown',
    hogwartsStaff: true,
    hogwartsStudent: false,
    house: 'Gryffindor',
    image: 'http://hp-api.herokuapp.com/images/lupin.jpg',
    name: 'Remus Lupin',
    patronus: 'wolf',
    species: 'werewolf',
    wand: {
      wood: 'cypress',
      core: 'unicorn tail-hair',
      length: 10.25,
    },
    wizard: true,
    yearOfBirth: 1960,
  },
  {
    actor: 'Dave Legeno',
    alive: true,
    // @ts-ignore
    alternate_actors: [],
    // @ts-ignore
    alternate_names: [],
    ancestry: '',
    dateOfBirth: '',
    eyeColour: '',
    gender: 'male',
    hairColour: 'grey',
    hogwartsStaff: false,
    hogwartsStudent: false,
    house: '',
    image: '',
    name: 'Fenrir Greyback',
    patronus: '',
    species: 'werewolf',
    wand: {wood: '', core: '', length: ''},
    wizard: true,
    yearOfBirth: '',
  },
]

export const expectedDummyDataForFilteredData: Record<
  string,
  any
> = [
  {
    actor: 'David Thewlis',
    alive: false,
    alternate_actors: [],
    alternate_names: [
      'Professor Lupin',
      'Moony',
      'Remus John Lupin',
    ],
    ancestry: 'half-blood',
    dateOfBirth: '10-03-1960',
    eyeColour: 'green',
    gender: 'male',
    hairColour: 'brown',
    hogwartsStaff: true,
    hogwartsStudent: false,
    house: 'Gryffindor',
    image: 'http://hp-api.herokuapp.com/images/lupin.jpg',
    name: 'Remus Lupin',
    patronus: 'wolf',
    species: 'werewolf',
    wand: {
      wood: 'cypress',
      core: 'unicorn tail-hair',
      length: 10.25,
    },
    wizard: true,
    yearOfBirth: 1960,
  },
  {
    actor: 'Dave Legeno',
    alive: true,
    alternate_actors: [],
    alternate_names: [],
    ancestry: '',
    dateOfBirth: '',
    eyeColour: '',
    gender: 'male',
    hairColour: 'grey',
    hogwartsStaff: false,
    hogwartsStudent: false,
    house: '',
    image: '',
    name: 'Fenrir Greyback',
    patronus: '',
    species: 'werewolf',
    wand: {wood: '', core: '', length: ''},
    wizard: true,
    yearOfBirth: '',
  },
]
